[workspace]
name = "biovat"
version = "0.0.1"
description = "A pipeline for population genomics analysis of non-model organisms"
authors = [
    "Verena Kutschera <verena.kutschera@nbis.se>",
    "Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>",
    "Cormac Kinsella <cormac.kinsella@nbis.se>",
    "André Soares <andre.soares@nbis.se>",
    "Jason Hill <jason.hill@nbis.se>",
    "Lorena Ament <lorena.ament@nbis.se>",
    "Per Unneberg <per.unneberg@nbis.se>",
    "Lucile Soler <lucile.soler@nbis.se>"
]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
nextflow = ">=26.4.6,<27"
nf-core = ">=4.0.3,<5"
nf-test = ">=0.9.5,<0.10"